addpath(genpath('@REL_PATH_TO_TOOL@'));
Misc = struct();
%Misc.Loads_path = 'external_loads.xml';
% TODO Misc.DofNames_Input: solve each leg separately.
% TODO Misc.MuscleNames_Input
Misc.DofNames_Input = {...
                       'hip_flexion_@SIDE@', ...
                       'knee_angle_@SIDE@', ...
                       'ankle_angle_@SIDE@', ...
                       };
%Misc.DofNames_Input = {...
%                       'hip_adduction_@SIDE@', ...
%                       'hip_rotation_@SIDE@', ...
%                       'hip_flexion_@SIDE@', ...
%                       'knee_angle_@SIDE@', ...
%                       'ankle_angle_@SIDE@', ...
%                       };
%Misc.DofNames_Input = {...
%                       'hip_flexion_@SIDE@', ...
%                       'knee_angle_@SIDE@', ...
%                       'ankle_angle_@SIDE@', ...
%                       };
Misc.MuscleNames_Input = {};
%Misc.MuscleNames_Input = {...
%    'soleus_r', ...
%    'med_gas_r', ...
%    'tib_ant_r' ...
%    };
% Misc.Mesh_Frequency = 20;
Misc.costfun = 'Exc_Act';
Misc.tendonStiffnessCoeff = 17.5;
tic;
[Time,MExcitation,MActivation,RActivation,TForcetilde,TForce,lMtilde,lM,MuscleNames,OptInfo,DatStore] = ...
SolveMuscleRedundancy_lMtildeState(...
    '@MODEL@', ... % model_path
    '@IK_SOLUTION@', ... % IK_path
    '@ID_SOLUTION@', ... % ID_path
    [@INIT_TIME@, @FINAL_TIME@], ... % time
    'results', ... % OutPath
    Misc);
    % TODO '', ... % ID_path
toc
save @STUDYNAME@_@NAME@_mrs.mat

